global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # YokedCache metrics endpoint
  - job_name: 'yokedcache'
    static_configs:
      - targets: ['yokedcache-dev:58000']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:56379']
    scrape_interval: 10s
